[package]
name = "runguard"
version = "0.1.0"
authors = ["huangyuhui", "Matrix contributors"]
edition = "2018"

[dependencies]
cgroups-rs = "0.2.3"
unshare = "0.6.0"
clap = "2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
nix = "0.11.0"
libc = "0.2.26"